run:
  timeout: 5m
  tests: true
  build-tags:
    - "!cgo"

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gofmt
    - goimports
    - misspell
    - unconvert
    - unparam
    - gocritic

linters-settings:
  goimports:
    local-prefixes: github.com/thiago2santos/go-pdf-converter
  
  gocritic:
    enabled-tags:
      - diagnostic
      - style
      - performance

issues:
  exclude-files:
    - ".*ocr_cgo\\.go$"
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - unparam
